In [0]:
import torch
from torch import nn
import Image
from PIL import Image
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2
import sklearn
import os
from skimage.color import rgb2gray
from skimage.filters import laplace, sobel, roberts

In [0]:
###Sobel Edge operator---edge detection operator based on gradient method  
###Laplacian Edge operator --- edge detection operator based on gradient methods but it calculated the second dervative
## of the data . It internally calls the sobel operator for first derivative.

In [2]:
print('Sobel operator:\n',np.matrix([[1,0,-1],[2,0,-2],[1,0,-1]]))
print('Laplacian operator:\n',np.matrix([[0,-1,0],[-1,4,-1],[0,-1,0]]))

Sobel operator:
 [[ 1  0 -1]
 [ 2  0 -2]
 [ 1  0 -1]]
Laplacian operator:
 [[ 0 -1  0]
 [-1  4 -1]
 [ 0 -1  0]]


In [0]:
###Sharp image
###Defocused image
###blurred image

In [0]:
s_path ='sharp/'
df_path='defocused_blurred/'
bl_path ='motion_blurred/'

img_paths = ['https://wirestock-prod.sfo2.digitaloceanspaces.com/public/81/gQFkGbHCD8DgTxiRuiOGNgCbHVHhCW49B9cJjNzK.jpeg?fbclid=IwAR0cessr2sk-f7eBAAi-vwwVYGPgivzR_Ef6177-DrGG1oLN5BytgxGJWmE']
 
def show_images(path):
    plt.figure(figsize=(10,10))
    for i in range(len(path)):
        x=plt.imread(path[i])
        plt.subplot(1, 3, i+1)
        plt.imshow(x)
        plt.xticks([])
        plt.yticks([])
    plt.tight_layout()
    plt.show()
     

In [0]:
def show_images(path):
    plt.figure(figsize=(10,10))
    for i in range(len(path)):
        x=cv2.imread(path[i],0)
        l = laplace(x)
        plt.subplot(1, 3, i+1)
        plt.imshow(l,cmap='gray')
        plt.xticks([])
        plt.yticks([])
    plt.tight_layout()
    plt.show()
 

In [0]:
def show_images(path):
    plt.figure(figsize=(10,10))
    for i in range(len(path)):
        x=cv2.imread(path[i],0)
        l = sobel(x)
        plt.subplot(1, 3, i+1)
        plt.imshow(l,cmap='gray')
        plt.xticks([])
        plt.yticks([])
    plt.tight_layout()
    plt.show()
 

In [12]:
sharp_images = os.listdir(s_path)
defocused = os.listdir(df_path)
motion_blurred = os.listdir(mot_path)

FileNotFoundError: ignored

In [12]:
   
def get_data(path,images)
 features=[]
    for img in images:
        feature=[]
        image_gray = cv2.imread(path+img,0)
        lap_feat = laplace(image_gray)
        sob_feat = sobel(image_gray)
        feature.extend([img,lap_feat.mean(),lap_feat.var(),np.amax(lap_feat),sob_feat.mean(),sob_feat.var(),np.max(sob_feat)])
        
        features.append(feature)
    return features

SyntaxError: ignored

In [0]:
###The mean, variance, maximum of the edge detected feature matrix are take 
###for each image appled on sobel and lapaclacian edge detection

sharp_features = get_data(s_path,sharp_images)
defocused_features = get_data(df_path,defocused)
motion_blur_features = get_data(mot_path,motion_blurred)

In [0]:
sharp_df = pd.read_csv('sharp_features.csv')
def_df = pd.read_csv('defocused_features.csv')
motblur_df = pd.read_csv('motionblurred_features.csv')
sharp_df.head()
sharp_df.drop('Unnamed: 0',axis=1,inplace=True)
motblur_df.drop('Unnamed: 0',axis=1,inplace=True)
def_df.drop('Unnamed: 0',axis=1,inplace=True)